export * from "./murivest";

export {
  appRolesTable,
  departmentsTable,
  appUsersTable,
  companiesTable,
  contactsTable,
  propertiesTable,
  mandatesTable,
  investorsTable,
  dealsTable,
  tasksTable,
  approvalsTable,
  meetingsTable,
  filesTable,
  dataRoomsTable,
  dataRoomAccessTable,
  legalMattersTable,
  invoicesTable,
  expensesTable,
  campaignsTable,
  emailTemplatesTable,
  emailSendsTable,
  auditLogsTable,
  notificationsTable,
  academyCoursesTable,
  academyLearningPathsTable,
  academyEnrollmentsTable,
  academyCertificationsTable,
} from "./murivest";
