export * from "./murivest";

export {
  appRolesTable,
  departmentsTable,
  usersTable as appUsersTable,
  companiesTable,
  contactsTable,
  propertiesTable,
  mandatesTable,
  investorsTable,
  dealsTable,
  tasksTable,
  approvalsTable,
  meetingsTable,
  documentsTable as filesTable,
  legalMattersTable,
  invoicesTable,
  expensesTable,
  campaignsTable,
  notificationsTable,
  activityTable as auditLogsTable,
  academyCoursesTable,
  academyLearningPathsTable,
  academyEnrollmentsTable,
  academyCertificationsTable,
} from "./murivest";
