import { useQuery } from "@tanstack/react-query";

const API_BASE = "/api";

async function fetchJson<T>(url: string): Promise<T> {
  const res = await fetch(url);
  if (!res.ok) throw new Error(`Failed to fetch ${url}`);
  return res.json();
}

export function useLookup(key: string) {
  return useQuery({
    queryKey: ["lookup", key],
    queryFn: () =>
      fetchJson<Array<{ value: string; label: string; id?: string }>>(
        `${API_BASE}/murivest/lookup/${key}`,
      ),
    staleTime: 30000,
  });
}

export const STATIC_OPTIONS = {
  contactCategory: [
    { value: "investor", label: "Investor" },
    { value: "landlord", label: "Landlord" },
    { value: "tenant", label: "Tenant" },
    { value: "broker", label: "Broker" },
    { value: "lawyer", label: "Lawyer" },
    { value: "banker", label: "Banker" },
    { value: "vendor", label: "Vendor" },
    { value: "partner", label: "Partner" },
    { value: "prospect", label: "Prospect" },
    { value: "other", label: "Other" },
  ],
  contactStatus: [
    { value: "new", label: "New" },
    { value: "contacted", label: "Contacted" },
    { value: "engaged", label: "Engaged" },
    { value: "qualified", label: "Qualified" },
    { value: "nurture", label: "Nurture" },
    { value: "proposal_sent", label: "Proposal Sent" },
    { value: "inactive", label: "Inactive" },
    { value: "converted", label: "Converted" },
    { value: "closed_lost", label: "Closed Lost" },
  ],
  propertyType: [
    { value: "office", label: "Office" },
    { value: "retail", label: "Retail" },
    { value: "mixed_use", label: "Mixed Use" },
    { value: "hotel", label: "Hotel" },
    { value: "industrial", label: "Industrial" },
    { value: "logistics", label: "Logistics" },
    { value: "land", label: "Land" },
    { value: "residential_block", label: "Residential Block" },
    { value: "other", label: "Other" },
  ],
  propertyStatus: [
    { value: "draft", label: "Draft" },
    { value: "under_review", label: "Under Review" },
    { value: "mandate_pending", label: "Mandate Pending" },
    { value: "active", label: "Active" },
    { value: "under_offer", label: "Under Offer" },
    { value: "published", label: "Published" },
    { value: "off_market", label: "Off Market" },
    { value: "closed", label: "Closed" },
    { value: "archived", label: "Archived" },
  ],
  mandateType: [
    { value: "exclusive", label: "Exclusive" },
    { value: "open", label: "Open" },
    { value: "co_broke", label: "Co-Broke" },
    { value: "advisory", label: "Advisory" },
    { value: "management", label: "Management" },
    { value: "ats_pending", label: "ATS Pending" },
  ],
  dealStage: [
    { value: "identified", label: "Identified" },
    { value: "qualified", label: "Qualified" },
    { value: "site_visit", label: "Site Visit" },
    { value: "loi", label: "LOI" },
    { value: "due_diligence", label: "Due Diligence" },
    { value: "closing", label: "Closing" },
    { value: "won", label: "Won" },
    { value: "lost", label: "Lost" },
  ],
  priority: [
    { value: "low", label: "Low" },
    { value: "medium", label: "Medium" },
    { value: "high", label: "High" },
    { value: "critical", label: "Critical" },
  ],
  taskStatus: [
    { value: "not_started", label: "Not Started" },
    { value: "in_progress", label: "In Progress" },
    { value: "blocked", label: "Blocked" },
    { value: "awaiting_review", label: "Awaiting Review" },
    { value: "completed", label: "Completed" },
    { value: "cancelled", label: "Cancelled" },
    { value: "overdue", label: "Overdue" },
  ],
  documentType: [
    { value: "Investor Brief", label: "Investor Brief" },
    { value: "Mandate", label: "Mandate" },
    { value: "LOI", label: "LOI" },
    { value: "Sale Agreement", label: "Sale Agreement" },
    { value: "Lease", label: "Lease" },
    { value: "NDA", label: "NDA" },
    { value: "KYC", label: "KYC" },
    { value: "Legal Opinion", label: "Legal Opinion" },
    { value: "Operations Manual", label: "Operations Manual" },
    { value: "Board Pack", label: "Board Pack" },
    { value: "Other", label: "Other" },
  ],
  confidentiality: [
    { value: "public", label: "Public" },
    { value: "internal", label: "Internal" },
    { value: "confidential", label: "Confidential" },
    { value: "restricted", label: "Restricted" },
    { value: "executive_only", label: "Executive Only" },
  ],
  approvalStatus: [
    { value: "draft", label: "Draft" },
    { value: "submitted", label: "Submitted" },
    { value: "review", label: "In Review" },
    { value: "approved", label: "Approved" },
    { value: "rejected", label: "Rejected" },
    { value: "archived", label: "Archived" },
  ],
  financeCategory: [
    { value: "Commission Revenue", label: "Commission Revenue" },
    { value: "Operating Cost", label: "Operating Cost" },
    { value: "Legal Payable", label: "Legal Payable" },
    { value: "Marketing Cost", label: "Marketing Cost" },
    { value: "HR Expense", label: "HR Expense" },
    { value: "IT Expense", label: "IT Expense" },
    { value: "Travel Expense", label: "Travel Expense" },
    { value: "Vendor Payment", label: "Vendor Payment" },
    { value: "Other", label: "Other" },
  ],
  legalMatterType: [
    { value: "Due Diligence", label: "Due Diligence" },
    { value: "Mandate", label: "Mandate" },
    { value: "Lease", label: "Lease" },
    { value: "Litigation", label: "Litigation" },
    { value: "Settlement", label: "Settlement" },
    { value: "Compliance", label: "Compliance" },
    { value: "Contract Review", label: "Contract Review" },
    { value: "ATS / Mandate", label: "ATS / Mandate" },
    { value: "Other", label: "Other" },
  ],
  legalStatus: [
    { value: "open", label: "Open" },
    { value: "in_review", label: "In Review" },
    { value: "awaiting_documents", label: "Awaiting Documents" },
    { value: "awaiting_signature", label: "Awaiting Signature" },
    { value: "pending_external_counsel", label: "Pending External Counsel" },
    { value: "closed", label: "Closed" },
    { value: "on_hold", label: "On Hold" },
  ],
  department: [
    { value: "Executive", label: "Executive" },
    { value: "Sales", label: "Sales" },
    { value: "Investor Relations", label: "Investor Relations" },
    { value: "Acquisitions", label: "Acquisitions" },
    { value: "Marketing", label: "Marketing" },
    { value: "Finance", label: "Finance" },
    { value: "Legal", label: "Legal" },
    { value: "Operations", label: "Operations" },
    { value: "HR", label: "HR" },
    { value: "IT", label: "IT" },
  ],
  owner: [
    { value: "Executive Admin", label: "Executive Admin" },
    { value: "Sales", label: "Sales" },
    { value: "Investor Relations", label: "Investor Relations" },
    { value: "Property Acquisition", label: "Property Acquisition" },
    { value: "Marketing", label: "Marketing" },
    { value: "Finance", label: "Finance" },
    { value: "Legal Operations", label: "Legal Operations" },
    { value: "Legal Counsel", label: "Legal Counsel" },
    { value: "General Counsel", label: "General Counsel" },
    { value: "Compliance Lead", label: "Compliance Lead" },
    { value: "HR / Academy", label: "HR / Academy" },
    { value: "IT / Product", label: "IT / Product" },
  ],
  campaignChannel: [
    { value: "email", label: "Email" },
    { value: "social", label: "Social Media" },
    { value: "field", label: "Field" },
    { value: "qr", label: "QR Code" },
    { value: "event", label: "Event" },
    { value: "multi_channel", label: "Multi-Channel" },
  ],
  campaignStatus: [
    { value: "draft", label: "Draft" },
    { value: "in_build", label: "In Build" },
    { value: "awaiting_approval", label: "Awaiting Approval" },
    { value: "approved", label: "Approved" },
    { value: "scheduled", label: "Scheduled" },
    { value: "launched", label: "Launched" },
    { value: "paused", label: "Paused" },
    { value: "completed", label: "Completed" },
    { value: "cancelled", label: "Cancelled" },
  ],
  dailyLogCategory: [
    { value: "Cold Outreach", label: "Cold Outreach" },
    { value: "Warm Outreach", label: "Warm Outreach" },
    { value: "Site Tour", label: "Site Tour" },
    { value: "LOI Drafted", label: "LOI Drafted" },
    { value: "Closing Documentation", label: "Closing Documentation" },
    { value: "Mandate Approval", label: "Mandate Approval" },
    { value: "Investor Update", label: "Investor Update" },
    { value: "Internal Meeting", label: "Internal Meeting" },
    { value: "Board Update", label: "Board Update" },
  ],
  jurisdiction: [
    { value: "Kenya", label: "Kenya" },
    { value: "Nigeria", label: "Nigeria" },
    { value: "Ghana", label: "Ghana" },
    { value: "South Africa", label: "South Africa" },
    { value: "Uganda", label: "Uganda" },
    { value: "Tanzania", label: "Tanzania" },
    { value: "Rwanda", label: "Rwanda" },
    { value: "Multi-jurisdiction", label: "Multi-jurisdiction" },
  ],
  accessTier: [
    { value: "public", label: "Public" },
    { value: "internal", label: "Internal" },
    { value: "confidential", label: "Confidential" },
    { value: "restricted", label: "Restricted" },
    { value: "executive_only", label: "Executive Only" },
    { value: "investor_portal", label: "Investor Portal" },
    { value: "landlord_portal", label: "Landlord Portal" },
    { value: "tenant_portal", label: "Tenant Portal" },
  ],
};

export type OptionKey = keyof typeof STATIC_OPTIONS;
